### ISSUE TITLE
Feladat beadás

### ISSUE THREAD

**Issue by vlagyivosztok** [Teaching-projects/SZE-FordProg-2021-Filter#2]

**Comment by hegyhati** [comment]
Szia! 

Megneztem, a kod tovabbra is elegge "fapados". Wikit nem latom sehogy sem. Amit tovabbra is hianyolok, az a levezetes, hogy konkretan mit implementaltal, illetve szeretnek latni egy szep bemutatasat annak, hogy milyen bemenetre milyen paranccsal milyen kimenet keletkezik. Erre valami van a readme-ben, meg van ket fajlod, de nem tunik kereknek a dolog.

Ezek nelkul most egy harmast tudok adni, ha ezek  felkerulnek,akkor egy 4-est.

**Comment by hegyhati** [comment]
E-mailes egyeztetesnek megfeleloen beirtam a kozepest.
